Uno call
Earving8/uno pull request #7
Opened 2019-04-18 15:56 UTC by EricESeitz

2019-04-19 18:50 UTC, TravisHull approved these changes

2019-04-19 18:59 UTC, CompSciLauren requested changes
Only have 1 comment to address. Code looks good!

2019-04-19 18:59 UTC, CompSciLauren commented on cards.js
> +    players[gameTurn].unoCall = 0;
Can we use a boolean here instead?

2019-04-19 20:22 UTC, Earving8 requested changes

2019-04-19 20:22 UTC, Earving8 commented on players.js
> +  this.playerUnoCall = unoCall;
You can just set this equal to 0 that way you don't have to pass in a parameter since Unocal just defaults to 0 on creation

2019-04-21 00:54 UTC, EricESeitz reviewed
Changed unoCall to boolean

2019-04-21 01:09 UTC, Earving8 approved these changes

2019-04-21 01:16 UTC, CompSciLauren approved these changes

2019-04-21 01:16 UTC, merged